# Generated by Django 4.2.13 on 2024-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('add_id', models.PositiveIntegerField(unique=True)),
                ('author', models.CharField(max_length=50)),
                ('views', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
            ],
        ),
    ]
